# Site settings
title: Hanley's Blog of Experiments
email: hanleyweng@gmail.com
main_site: hanleyweng.com
main_site_url: http://hanleyweng.com
description: > # this means to ignore newlines until "baseurl:"
  Hanley Weng's Process Blog. A personal journal of creative work with emerging technologies. Here be experiments in Interactive Media Art, Physical Installations, Games, Machine Learning, Algorithms, Data Visualisation, Maps, etc.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://hanleyweng.github.io" # the base hostname & protocol for your site
twitter_username: hanleyweng
github_username:  hanleyweng

# Build settings
markdown: kramdown

# Permalink
permalink: /:categories/:title.html

# Excludes - (Wow! Including these reduced render time from 90 to 13 seconds)
exclude: ["*_private", "*_private*","_TO UPLOAD*", "_TO BE UPLOADED*"]

include: ["_posts_assets"]