# Site settings
title: Hanley's Blog
email: hanleyweng@gmail.com
main_site: hanleyweng.com
main_site_url: http://hanleyweng.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Hanley Weng, an Interaction Designer. This is a journal of work, processes, thoughts, and learnings. Here be Interactive Art Installations, Data Visualisations, Visual Explorations, Design Computing, and experiments in Interaction Design. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://hanleyweng.github.io" # the base hostname & protocol for your site
twitter_username: hanleyweng
github_username:  hanleyweng

# Build settings
markdown: kramdown

# Permalink
permalink: /:categories/:title.html

# Excludes - (Wow! Including these reduced render time from 90 to 13 seconds)
exclude: ["*_private", "*_private*","_TO UPLOAD*", "_TO BE UPLOADED*"]

include: ["_posts_assets", "_cover_image"]

# Plugins: 
# https://help.github.com/articles/configuring-jekyll-plugins/
# https://jekyllrb.com/docs/plugins/
